
- id: doi:10.1007/s12021-024-09678-2
  date: "2024-10-10"
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1007%2Fs12021-024-09678-2/MediaObjects/12021_2024_9678_Fig6_HTML.png
  extra-links:
    - type: journal
      link: https://link.springer.com/article/10.1007/s12021-024-09678-2
    - type: source
      link: https://github.com/hmynssen/Stitcher
  tags:
    - computational methods
    - compared neuroanatomy
    - brain morphology
    - cortical folding
  
- id: doi:10.1016/j.neuroimage.2020.117546
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1053811920310314-gr3_lrg.jpg
  date: 2021-2-1
  extra-links:
    - type: journal
      link: https://www.sciencedirect.com/science/article/pii/S1053811920310314
  tags:
    - brain morphology
    - cortical folding

- id: doi:10.1073/pnas.1716956116
  date: 2019-7-8
  extra-links:
    - type: journal
      link: https://www.pnas.org/content/116/30/15253.short
  tags:
    - compared neuroanatomy
    - brain morphology
    - cortical folding 

- id: doi:10.1038/s42003-019-0421-7
  date: 2019-5-20 
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/s42003-019-0421-7
    - type: source
      link: https://doi.org/10.5281/zenodo.2595060
  tags:
    - brain morphology
    - cortical folding 

- id: doi:10.1073/pnas.1610175113
  date: 2016-11-8 
  extra-links:
    - type: journal
      link: https://www.pnas.org/content/113/45/12820.short
  tags:
    - brain morphology
    - cortical folding 

- id: doi:10.1126/science.aaa9101
  date: 2015-7-3
  extra-links:
    - type: journal
      link: https://science.sciencemag.org/content/349/6243/74.abstract
  tags:
    - compared neuroanatomy
    - brain morphology
    - cortical folding 

- id: doi:10.1101/2022.01.10.22268812
  image: https://www.medrxiv.org/content/medrxiv/early/2022/01/12/2022.01.10.22268812/F1.large.jpg
  date: 2022-1-11
  extra-links:
    - type: preprint
      link: https://www.medrxiv.org/content/10.1101/2022.01.10.22268812v2
  tags:
    - brain morphology
    - cortical folding 
    - neurodegenerative diseases
    
- id: doi:10.3389/fnins.2022.897226
  date: 2022-7-18
  extra-links:
    - type: journal
      link: https://www.frontiersin.org/articles/10.3389/fnins.2022.897226/full
  tags:
    - cortical folding
    - aging
    - neurodegenerative diseases
    - harmonization
    - baseline estimation

- id: doi:10.1101/2022.07.07.499214
  date: 2022-7-7
  extra-links:
    - type: preprint
      link: https://www.biorxiv.org/content/10.1101/2022.07.07.499214v1
  tags:
    - PCA
    - cortical folding model
    - cortical folding universal rule
    - compared neuroanatomy

- id: doi:10.48550/arXiv.2209.08066
  date: 2022-9-16
  extra-links:
    - type: preprint
      link: https://arxiv.org/abs/2209.08066
  tags:
    - brain morphology
    - cortical folding
    - compared neuroanatomy
