- id: doi:10.1016/j.neuroimage.2020.117546
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1053811920310314-gr3_lrg.jpg
  date: 2021-2-1
  extra-links:
    - type: journal
      link: https://www.sciencedirect.com/science/article/pii/S1053811920310314
  tags:
    - brain morphology
    - cortical folding

- id: doi:10.1126/science.aaa9101
  date: 2015-7-3
  extra-links:
    - type: journal
      link: https://science.sciencemag.org/content/349/6243/74.abstract
  tags:
    - compared neuroanatomy
    - brain morphology
    - cortical folding 

- id: doi:10.1038/s42003-019-0421-7
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/s42003-019-0421-7
    - type: source
      link: https://doi.org/10.5281/zenodo.2595060
    tags:
    - compared neuroanatomy
    - brain morphology
    - cortical folding 

